### ISSUE TITLE
multisafepay_orderdata hook not working correctly. Patch wasn't applied completely

### ISSUE THREAD

**Issue by SuperDiglett** [MultiSafepay/drupal-commerce-2#2]
Something went wrong when merging this [patch](https://www.drupal.org/files/issues/2020-03-03/alter-orderdata-3117420-4.patch) into master. 

The following alteration has not been applied:
```
@@ -238,6 +244,8 @@ class OrderHelper {
       ],
     ];
 
+    $this->moduleHandler->alter(['multisafepay_orderdata_' . strtolower($gatewayCode), 'multisafepay_orderdata'], $orderData, $payment, $gatewayInfo);
+
     return $orderData;
   }
```

**Comment by SuperDiglett** [comment]
Fixed with the following [MR](https://github.com/MultiSafepay/drupal-commerce-2/pull/3/checks?check_run_id=712876679), but your CodeSniffer is not functioning properly.

**Comment by Jasper-MultiSafepay** [comment]
Has been merged and released
