### ISSUE TITLE
Make use of semantic versioning due to Drupal 8 and Drupal 9 compatibility.

### ISSUE THREAD

**Issue by SuperDiglett** [MultiSafepay/drupal-commerce-2#4]
Since the release of Drupal 9 and the latest version of the module is compatible with Drupal 8 and Drupal 9, semantic versioning should be used. More info: https://www.drupal.org/docs/updating-drupal/how-to-prepare-your-drupal-7-or-8-site-for-drupal-9/preparing-drupalorg

So `8.x.2.0` should be `2.0.0`

**Comment by Jasper-MultiSafepay** [comment]
@kevinvhengst 
Thanks, looked into this, seems like we are required to increment the major version too for this.
So it will become 3.0.0
Trying to create 2.0.0 will result in 
![image](https://user-images.githubusercontent.com/26003384/89439813-02570d80-d74b-11ea-890e-04e7559e9053.png)

We'll add it into our next sprint

**Comment by SuperDiglett** [comment]
@Jasper-MultiSafepay 

Fair enough, sounds good!

**Comment by Jasper-MultiSafepay** [comment]
Fixed with https://github.com/MultiSafepay/drupal-commerce-2/releases/tag/3.0.0
