### ISSUE TITLE
Not possible to add custom MSP gateways

### ISSUE THREAD

**Issue by SuperDiglett** [MultiSafepay/drupal-commerce-2#5]
It is not possible to implement a custom gateway without patching it into the constant `MSP_GATEWAYS` in `src/Helpers/GatewayHelper.php` on `line 16`. Developers might want to add custom gateways because MSP has created a custom gateway for a merchant, for instance when the merchant has their own giftcard provided by a MSP partner.

Solution would be that this would not be defined as a constant, because it's not consant and a hook is created which makes you able to add a custom gateway for when the list of available MSP gateways is fetched.

**Comment by Jasper-MultiSafepay** [comment]
Should be fixed with https://github.com/MultiSafepay/drupal-commerce-2/releases/tag/3.0.0
We have now added a generic gateway which can be used for custom gateways
